//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedLibTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIME-Version: 1.0
        ///Date: Fri, 23 Sep 2022 09:51:16 +0200
        ///Message-ID: &lt;CANY3bHNCowtzhX7RwD0g5_Xsv66s59O-X0-QuUNcGxLByB4wmA@mail.gmail.com&gt;
        ///Subject: sonar cloud
        ///From: Si Carter &lt;s1cart3r@gmail.com&gt;
        ///To: s1cart3r@gmail.com
        ///Content-Type: multipart/alternative; boundary=&quot;00000000000066df2505e953716d&quot;
        ///
        ///--00000000000066df2505e953716d
        ///Content-Type: text/plain; charset=&quot;UTF-8&quot;
        ///
        ///https://sonarcloud.io/project/issues?resolved=false&amp;types=VULNERABILITY&amp;id=k3ldar_.NetCorePluginManager
        ///
        ///--00000000000066df2505e9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GMailMail {
            get {
                return ResourceManager.GetString("GMailMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered-To: s1cart3r@gmail.com
        ///Received: by 2002:a02:9988:0:b0:364:450:fe3 with SMTP id a8csp4506812jal;
        ///        Wed, 2 Nov 2022 00:40:16 -0700 (PDT)
        ///X-Google-Smtp-Source: AMsMyM6wodpPk0wVEJYsANF5VPUyUwZB/SVrZgr30eFXfvhHBvhisU35KTSTSFQqkJsYC/vVfaZI
        ///X-Received: by 2002:aa7:c3ca:0:b0:463:4784:bcec with SMTP id l10-20020aa7c3ca000000b004634784bcecmr16060177edr.315.1667374815853;
        ///        Wed, 02 Nov 2022 00:40:15 -0700 (PDT)
        ///ARC-Seal: i=2; a=rsa-sha256; t=1667374815; cv=pass;
        ///        d=google.com; s=ar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OtherMail {
            get {
                return ResourceManager.GetString("OtherMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received: from AM0PR09MB3939.eurprd09.prod.outlook.com (2603:10a6:208:19d::7)
        /// by AM9PR09MB4673.eurprd09.prod.outlook.com with HTTPS; Tue, 1 Nov 2022
        /// 17:47:20 +0000
        ///ARC-Seal: i=2; a=rsa-sha256; s=arcselector9901; d=microsoft.com; cv=pass;
        /// b=Dv06KbOnCkmJCwmc6O0UyxH7riZMRwJEATGjlRQZE+jew19yNyjUNRkwF/d6/9LTbHIRH+78P/K2y0g4CQBuJcEP0FTkSp24UHnQxOl3pkN5zrz6Ud9LP7TwZ71UadIB0RcbHFeabytliChDVOHAmWto6BkrabSXdwRgWDhq4RRsNFCfOCYY4EsuJJQgd6t+GnrI3ZahvNOupw0MEyuF8YBKAj3M2uSRE8jfBGwFt1etRysSOwhzJ4U1nboBc3jB6I5m0/1Mz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string outlookmail {
            get {
                return ResourceManager.GetString("outlookmail", resourceCulture);
            }
        }
    }
}
